FROM alpine:latest

RUN apk update; apk add python3; apk add py3-pip

WORKDIR /tweetgenerator
RUN wget https://raw.githubusercontent.com/buaalqh/tweetoscope/master/estimator/logger.py
RUN pip3 install kafka-python
RUN pip3 install argparse
RUN pip3 install termcolor

CMD python3 logger.py --broker-list localhost:9092
