FROM qihaoliu/tweetoscope:gaml-cappkafka-v1

WORKDIR /tweetgenerator
RUN wget https://raw.githubusercontent.com/buaalqh/tweetoscope/master/dataset/news-data.csv
RUN wget https://raw.githubusercontent.com/buaalqh/tweetoscope/master/dataset/news-index.csv
RUN wget https://raw.githubusercontent.com/buaalqh/tweetoscope/master/generator/tweetoscopeGenerator.hpp
RUN wget https://raw.githubusercontent.com/buaalqh/tweetoscope/master/generator/tweet-generator.cpp
RUN wget https://raw.githubusercontent.com/buaalqh/tweetoscope/master/param/params-generator.config

RUN sed -i 's:/home/lqh/sdi/tweetscope_groupe8/tweetoscope/dataset:/tweetgenerator:' /tweetgenerator/params-generator.config

RUN g++ -o tweet-generator tweet-generator.cpp -O3 $(pkg-config --cflags --libs gaml) -lpthread -lcppkafka -lrdkafka

CMD ./tweet-generator params-generator.config 

##docker run --rm -it --network host qihaoliu/tweetoscope:generator-v1
